# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86e21278efd488d0db89ee6583ac10ccf8bee7f7e7a78de68b9da46310c5c41dbbba2b7e836495caa4dcfa7b4b6a8e21545755763cc276107dcbbfb2dd061fc6

test:
  secret_key_base: b351531adf6e8f262c263b2da2d1e0c7e89fffc2b49e72f823b0b740ff72e5ce1890c42e20069af74c5042b2f50d01a94ba1b95773687327f0ee9867b8e78e83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
